import "../globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const messages = await getMessages();

export default function LightLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <div className="w-[80%] mx-auto pt-12">
          <NextIntlClientProvider messages={messages}>
            <Navbar variant="light" />
            <main className="py-12 md:py-24">{children}</main>
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  );
}
