import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import "../globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function DarkLayout({ children, params: { locale } }) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="min-h-screen bg-black text-white antialiased">
        <div className="w-[80%] mx-auto pt-12">
          <NextIntlClientProvider messages={messages}>
            <Navbar variant="black" />
            <main className="py-12 md:py-24">{children}</main>
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  );
}
