import "../globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DarkLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black text-white antialiased">
        <div className="w-[90%] mx-auto pt-12">
          <Navbar variant="black" />
          <main className="py-24">{children}</main>
        </div>
      </body>
    </html>
  );
}
