import Sidebar from "@/components/admin/Sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.locale}>
      <body>
        <div className="flex items-center w-full">
          <Sidebar />
          <div className="p-12 w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
