import Sidebar from "@/components/admin/Sidebar";
import { routing } from "@/i18n/routing";
import { hasLocale } from "next-intl";
import { Roboto } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
  variable: "--font-roboto",
});

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={params.locale}>
      <body className={roboto.className}>
        <div className="flex w-full">
          <Sidebar />
          <div className="w-full p-12">{children}</div>
        </div>
      </body>
    </html>
  );
}
