import Sidebar from "@/components/admin/Sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-center">
          <Sidebar />
          <div className="p-12">{children}</div>
        </div>
      </body>
    </html>
  );
}
